//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSubtitlesDotNET {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenSubtitlesDotNET.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;OSLanguageTableDump&gt;
        ///  &lt;language&gt;
        ///    &lt;IdSubLanguage&gt;aar&lt;/IdSubLanguage &gt;
        ///    &lt;ISO639&gt;aa&lt;/ISO639 &gt;
        ///    &lt;LanguageName&gt;Afar afar&lt;/LanguageName &gt;
        ///    &lt;UploadEnabled&gt;0&lt;/UploadEnabled &gt;
        ///    &lt;WebEnabled&gt;0&lt;/WebEnabled &gt;
        ///  &lt;/language&gt;
        ///  &lt;language&gt;
        ///    &lt;IdSubLanguage&gt;abk&lt;/IdSubLanguage &gt;
        ///    &lt;ISO639&gt;ab&lt;/ISO639 &gt;
        ///    &lt;LanguageName&gt;Abkhazian&lt;/LanguageName &gt;
        ///    &lt;UploadEnabled&gt;0&lt;/UploadEnabled &gt;
        ///    &lt;WebEnabled&gt;0&lt;/WebEnabled &gt;
        ///  &lt;/language&gt;
        ///  &lt;language&gt;
        ///    &lt;IdS [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string OSLanguageTableDump {
            get {
                return ResourceManager.GetString("OSLanguageTableDump", resourceCulture);
            }
        }
    }
}
